Lesson18 branch
insrf/test-guru pull request #17
Opened 2018-04-24 15:47 UTC by insrf

2018-04-24 18:03 UTC, psylone requested changes

2018-04-24 18:03 UTC, psylone commented on app/assets/javascripts/utilities/timer.js
> + elem.innerHTML--
Может быть `null`.

2018-04-24 18:03 UTC, psylone commented on db/schema.rb
> +    t.boolean "timer_on", default: false
Можно отталкиваться от значения в атрибуте `timer`. Если там `nil`, значит таймера нет.

2018-04-24 18:03 UTC, psylone commented on app/assets/javascripts/utilities/timer.js
> +setTimeout(timer,1000)
Есть некоторая вероятность, что тело страницы не успеет загрузиться за 1 секунду. Лучше стартовать таймер по событию `turbolinks:load`.

2018-04-24 18:03 UTC, psylone commented on app/assets/javascripts/utilities/timer.js
> +   setTimeout(timer,1000)
Можно использовать `setInterval`.

2018-04-24 18:03 UTC, psylone commented on app/models/test_passage.rb
> +    self.test.timer.hour * 3600 + self.test.timer.min * 60
Лучше либо сразу хранить кол-во секунд, либо время до которого разрешается прохождение теста.

2018-04-24 18:03 UTC, psylone commented on app/models/test_passage.rb
> +  def correcting_timer
Название метода неочевидно.

2018-04-24 18:07 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    if @test_passage.completed? || (@test_passage.timeout < 0)
Нужно сначала проверять не вышло ли время и только потом принимать ответ.

2018-04-27 15:08 UTC, insrf commented on db/schema.rb
> +    t.boolean "timer_on", default: false
Это довольно сложно. Во вьюхе new_test я использовал, как мне показалось удобные
    <%= form.label :timer %><br>
    <%= form.time_select :timer%>
для создания таймера. 
Т.е. в любом случае поля будут не nil. Это грубая ошибка?

2018-04-30 12:34 UTC, psylone commented on db/schema.rb
> +    t.boolean "timer_on", default: false
Это не ошибка вовсе. Можно, например, сделать чекбокс использовать ли таймер и если чекбокс не выбран - игнорировать параметры таймера.

2018-04-30 12:34 UTC, psylone approved these changes

2018-04-30 12:36 UTC, psylone commented on app/controllers/admin/tests_controller.rb
> +     return nil
`return` не нужен, достаточно условного выражения:

```ruby
def convert_time_to_integer
  if params[:timer_on]
    params["timer_params(4i)"].to_i * 3600 + params["timer_params(5i)"].to_i * 60
  end
end
```

2018-04-30 12:38 UTC, psylone commented on db/schema.rb
> +    t.boolean "timer_on", default: false
Имел в виду с точки зрения модели. На клиенте можно сделать чекбокс нужно ли использовать таймер, но в базе дополнительно этот признак не хранить. Просто не устанавливать значение в атрибуте `timer`.

2018-04-30 12:39 UTC, psylone commented on db/schema.rb
> +    t.boolean "timer_on", default: false
Собственно, ты так и сделал.

2018-05-01 07:21 UTC, merged