Lesson19 branch
insrf/test-guru pull request #18
Opened 2018-05-13 08:22 UTC by insrf

2018-05-13 13:20 UTC, psylone requested changes

2018-05-13 13:20 UTC, psylone commented on app/controllers/admin/user_bages_controller.rb
> +class Admin::UserBagesController < Admin::BaseController
Зачем нам этот контроллер? Если для того чтобы администратор мог присваивать бэйджи пользователю постфактум то для этого лучше сделать отдельный экшен в `Admin::BadgesController`.

2018-05-13 13:20 UTC, psylone commented on app/controllers/bages_controller.rb
> +class BagesController < ApplicationController
Как пользователь сможет посмотреть список полученных бэйджей на данный момент?

2018-05-13 13:20 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +                :set_first_test_complited_test_badge, only: %i[result]
А если по какой-то причине случится сетевой сбой после успешного прохождения теста но перед редиректом? В этом случае бэйдж не будет выдан.

2018-05-13 13:20 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +                :set_first_test_complited_test_badge, only: %i[result]
Самое основное здесь - не стоит для подобной логики использовать обратные выводы. Например, при добавлении нового правила придётся изменять код контроллера, это не очевидно. Далее - обязанность контроллера в оркестрации запроса, никакого отношения к бизнес-логике контроллер не имеет. Таким образом, за раздачу бэйджей должна отвечать отдельная абстракция, например, Ruby-класс.

2018-05-13 13:20 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    @user_bages.save
Используй добавление объекта с помощью метода ассоциации: `current_user.badges.push(badge)`.

2018-05-13 13:20 UTC, psylone commented on app/controllers/user_bages_controller.rb
> +class UserBagesController < ApplicationController
Этот контроллер также избыточен.

2018-05-13 13:20 UTC, psylone commented on db/schema.rb
> +    t.integer "number_of_rule"
Для чего хранить отдельно номер правила?

2018-05-13 13:20 UTC, psylone commented on app/helpers/bages_helper.rb
> +    RULE_SELECT[key]
Зачем в строковом поле хранить число и затем постоянно приводить его с помощью `to_i`? Можно хранить в строковом поле `rule` у бэйджа некоторый лэйбл (название) правила: `all_tests_passed`, `passed_on_the_first_attempt`. Этой информации достаточно. Если нужно отобразить более подробное название правила, стоит использвать файлы локализации, а название правила бэйджа будет как раз ключом локализации. Если нужно реализовать правила одинаковые по логике но с разной тематикой, как например все пройденные тесты по истории и математике, то это должно быть одно и то же правило с разными категориями. Название категории при этом будет храниться в отдельном атрибуте. Это позволит реализовать один метод обработки данного правила который будет опираться на параметр. То же самое касается уровня теста.

2018-05-15 14:45 UTC, insrf commented on app/controllers/admin/user_bages_controller.rb
> +class Admin::UserBagesController < Admin::BaseController
Я добавил экшен для присваивания бейджей. Просто в отдельном контроллере их можно редактировать и удалять. Ведь может возникнуть потребность удалить бейджи, например, если администратор случайно присвоить не тот бейдж или не тому. Или нужно еще добавить экшен удаления и редактирования?

2018-05-15 14:50 UTC, insrf commented on app/controllers/bages_controller.rb
> +class BagesController < ApplicationController
Дело в том, что в контроллере user_badges для пользователя я сделал поиск параметров сразу по current_user.id. И пользователей при просмотре user_bages index видит только свои бейджи. 
@user_bages = UserBage.where(user_id: current_user.id)
P.S. Для просмотра полного списка бейджей я добавил index для user

2018-05-17 09:01 UTC, psylone commented on app/controllers/bages_controller.rb
> +class BagesController < ApplicationController
`current_user.badges` выдаст список бэйджей текущего пользователя.

2018-05-18 10:28 UTC, psylone requested changes

2018-05-18 10:28 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +  def set_badge(current_user, test_passage)
Вызывай `AssignRuleBadge` прямо из метода контроллера, отдельный метод-обёртку для этого делать не нужно.

2018-05-18 10:28 UTC, psylone commented on app/services/assign_rule_bage.rb
> +    @current_user = current_user
Достаточно передавать объект `test_passsage`, пользователя можно получить с помощью метода ассоциации.

2018-05-18 10:28 UTC, psylone commented on app/services/assign_rule_bage.rb
> +    if all_some_category_test_passed("mathematics")
Методы-предикаты удобно называть с окончанием на `?`.

2018-05-18 10:28 UTC, psylone commented on app/services/assign_rule_bage.rb
> +  def call
По сути только `call` является публичным методом. Это интерфейс нашего сервиса. Все остальные методы сервиса стоит сделать приватными.

2018-05-18 10:28 UTC, psylone commented on app/services/assign_rule_bage.rb
> +    set_level_hard_badge
Здесь есть некоторая проблема. При добавлении нового правила нам придётся вносить множество изменений. Например, если у нас появится ещё один уровень сложности, нам придётся изменить код сервиса здесь, добавить правило в коллекцию выбора для админа.

По сути же новый уровень сложности - это уже существующее правило только для другого уровня. Ты молодец что сделал общий метод проверки условия выдачи бэйджа - это верный ход. Но нужно довести этот момент до финишной прямой.

Чтобы улучшить и упростить архитектуру нашего сервиса нам понадобится хранить в таблице бэйджей 2 поля. Оба строковых, первое из них это идентификатор бэйдж, второе - значение параметра. Например, `Badge[:all_tests_by_level, 1]`. Мы также можем добавить такой же бэйдж с тем же правилом, но с уровнем 2.

Для того чтобы получить список всех правил для вывода в админке можно сделать метод класса у бэйджа примерно такой: `distinct.pluck(:rule_name)`. То есть мы отсылаем прямой запрос в базу чтобы получить массив с названиями правил без дубликатов.

Теперь что касается сервиса. У тебя правильных ход мыслей, но нам нужно избавиться от необходимости изменять код сервиса при добавлении бэйджа с существующим правилом, но с другим значением. То есть, если мы добавим бэйдж за все успешно пройденные тесты данной категории с новой категорией, код сервиса не изменится. Но если добавим именно новую логику вместе с правилом тогда да, придётся добавить метод в сервис, но всего лишь единственный метод. Исходя из этого код сервиса может быть примерно таким:

```ruby
class AssignBadges
  def initialize(test_passage)
    @test_passage = test_passage
  end

  def call
    Badge.find_each do |badge|
      add_badge!(badge) if send("#{badge.rule_name}_achieved?", rule_value)
    end
  end

  private

  def all_tests_by_level_achieved?(rule_value)
  end
end
```

Таким образом, если нам нужно будет добавить логику для нового правила, всё что нам потребуется - это добавить метод-предикат в сервис и всё.

2018-05-20 22:14 UTC, psylone approved these changes

2018-05-20 22:14 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +  def set_badge(test_passage)
В принципе, можно обойтись без этого метода - вызывай `AssignRuleBadge` прямо внутри экшена, это норм.

2018-05-20 22:14 UTC, psylone commented on app/helpers/bages_helper.rb
> +  RULE_SELECT = ['all some category tests passed',
Поскольку названия правил хранятся в бэйджах, можно сделать для селекта примерно такой метод:

```ruby
Badge.distinct.pluck(:rule)
```

2018-05-20 22:14 UTC, psylone commented on app/services/assign_rule_bage.rb
> +      add_badge!(badge) if send("#{badge.rule}_achieved?", badge.rule_value)
Совсем другое дело!

2018-07-04 17:31 UTC, closed without merging